# Makefile for R-Mobile framebuffer device driver
#
obj-y +=  panel_register_config.o panel_common.o s6e88a0_backlight.o dynamic_aid.o
obj-$(CONFIG_LDI_MDNIE)        += mdnie.o mdnie_tuning.o
obj-$(CONFIG_FB_R_MOBILE_VX5B3D)       += panel_vx5b3d.o
