/*
 * drivers/video/r-mobile/panel/panel_nt35590.h
 *
 * Copyright (C) 2014 Broadcom Corporation
 * All rights reserved.
 *
 */

#include "panel_common.h"

#define NT35590_HS_TRAIL_NS 60
#define NT35590_HS_TRAIL_UI 4
#define NT35590_HS_TRAIL_ADJUST (25*PRECISION_FACT)
#define NT35590_HSPPVL_NS 40
#define NT35590_HSPPVL_UI 4
#define NT35590_CKTRVL_NS 60
#define NT35590_CKPPVL_NS 38
#define NT35590_HSZEROVL_NS 145
#define NT35590_HSZEROVL_UI 10
#define NT35590_CKPOSTVL_NS 60
#define NT35590_CKPOSTVL_UI 52
#define NT35590_CKPREVL_NS 1
#define NT35590_CKPREVL_UI 8

static struct screen_disp_time_param nt35590_time_param __initdata = {
	.hstrial_ns = NT35590_HS_TRAIL_NS,
	.hstrial_ui = NT35590_HS_TRAIL_UI,
	.hstrial_adj = NT35590_HS_TRAIL_ADJUST,
	.hsppvl_ns = NT35590_HSPPVL_NS,
	.hsppvl_ui = NT35590_HSPPVL_UI,
	.cktrvl_ns = NT35590_CKTRVL_NS,
	.ckppvl_ns = NT35590_CKPPVL_NS,
	.hszerovl_ns = NT35590_HSZEROVL_NS,
	.hszerovl_ui = NT35590_HSZEROVL_UI,
	.ckpostvl_ns = NT35590_CKPOSTVL_NS,
	.ckpostvl_ui = NT35590_CKPOSTVL_UI,
	.ckprevl_ns = NT35590_CKPREVL_NS,
	.ckprevl_ui = NT35590_CKPREVL_UI,
};

#define NT35590_TE_SCAN_LINE 1279

static struct dispctrl_rec nt35590_initialize_cmd[] __initdata = {

	 {DISPCTRL_WR_CMND, 0xFF},
	 {DISPCTRL_WR_DATA, 0xEE},

	 {DISPCTRL_WR_CMND, 0xFB},
	 {DISPCTRL_WR_DATA, 0x01},

	 {DISPCTRL_WR_CMND, 0x12},
	 {DISPCTRL_WR_DATA, 0x50},

	 {DISPCTRL_WR_CMND, 0x13},
	 {DISPCTRL_WR_DATA, 0x02},

	 {DISPCTRL_WR_CMND, 0x6A},
	 {DISPCTRL_WR_DATA, 0x60},

	 {DISPCTRL_WR_CMND, 0x05},
	 {DISPCTRL_WR_DATA, 0x59},

	 {DISPCTRL_WR_CMND, 0xFF},
	 {DISPCTRL_WR_DATA, 0x01},

	 {DISPCTRL_WR_CMND, 0xFB},
	 {DISPCTRL_WR_DATA, 0x01},

	 {DISPCTRL_WR_CMND, 0x00},
	 {DISPCTRL_WR_DATA, 0x4A},

	 {DISPCTRL_WR_CMND, 0x01},
	 {DISPCTRL_WR_DATA, 0x33},

	 {DISPCTRL_WR_CMND, 0x02},
	 {DISPCTRL_WR_DATA, 0x53},

	 {DISPCTRL_WR_CMND, 0x03},
	 {DISPCTRL_WR_DATA, 0x55},

	 {DISPCTRL_WR_CMND, 0x04},
	 {DISPCTRL_WR_DATA, 0x55},

	 {DISPCTRL_WR_CMND, 0x05},
	 {DISPCTRL_WR_DATA, 0x33},

	 {DISPCTRL_WR_CMND, 0x06},
	 {DISPCTRL_WR_DATA, 0x22},

	 {DISPCTRL_WR_CMND, 0x08},
	 {DISPCTRL_WR_DATA, 0x56},

	 {DISPCTRL_WR_CMND, 0x09},
	 {DISPCTRL_WR_DATA, 0x8F},

	 {DISPCTRL_WR_CMND, 0x36},
	 {DISPCTRL_WR_DATA, 0x73},

	 {DISPCTRL_WR_CMND, 0x0B},
	 {DISPCTRL_WR_DATA, 0xCF},

	 {DISPCTRL_WR_CMND, 0x0C},
	 {DISPCTRL_WR_DATA, 0xCF},

	 {DISPCTRL_WR_CMND, 0x0D},
	 {DISPCTRL_WR_DATA, 0x2F},

	 {DISPCTRL_WR_CMND, 0x0E},
	 {DISPCTRL_WR_DATA, 0x29},

	 {DISPCTRL_WR_CMND, 0x11},
	 {DISPCTRL_WR_DATA, 0x86},

	 {DISPCTRL_WR_CMND, 0x12},
	 {DISPCTRL_WR_DATA, 0x03},

	 {DISPCTRL_WR_CMND, 0x71},
	 {DISPCTRL_WR_DATA, 0x2C},

	 {DISPCTRL_WR_CMND, 0x6F},
	 {DISPCTRL_WR_DATA, 0x03},

	 {DISPCTRL_WR_CMND, 0x0F},
	 {DISPCTRL_WR_DATA, 0x0A},
	/* LPTS timing*/

	 {DISPCTRL_WR_CMND, 0xFF},
	 {DISPCTRL_WR_DATA, 0x05},

	 {DISPCTRL_WR_CMND, 0xFB},
	 {DISPCTRL_WR_DATA, 0x01},

	 {DISPCTRL_WR_CMND, 0x01},
	 {DISPCTRL_WR_DATA, 0x00},

	 {DISPCTRL_WR_CMND, 0x02},
	 {DISPCTRL_WR_DATA, 0x82},

	 {DISPCTRL_WR_CMND, 0x03},
	 {DISPCTRL_WR_DATA, 0x82},

	 {DISPCTRL_WR_CMND, 0x04},
	 {DISPCTRL_WR_DATA, 0x82},

	 {DISPCTRL_WR_CMND, 0x05},
	 {DISPCTRL_WR_DATA, 0x30},

	 {DISPCTRL_WR_CMND, 0x06},
	 {DISPCTRL_WR_DATA, 0x33},

	 {DISPCTRL_WR_CMND, 0x07},
	 {DISPCTRL_WR_DATA, 0x01},

	 {DISPCTRL_WR_CMND, 0x08},
	 {DISPCTRL_WR_DATA, 0x00},

	 {DISPCTRL_WR_CMND, 0x09},
	 {DISPCTRL_WR_DATA, 0x46},

	 {DISPCTRL_WR_CMND, 0x0A},
	 {DISPCTRL_WR_DATA, 0x46},

	 {DISPCTRL_WR_CMND, 0x0D},
	 {DISPCTRL_WR_DATA, 0x0B},

	 {DISPCTRL_WR_CMND, 0x0E},
	 {DISPCTRL_WR_DATA, 0x1D},

	 {DISPCTRL_WR_CMND, 0x0F},
	 {DISPCTRL_WR_DATA, 0x08},

	 {DISPCTRL_WR_CMND, 0x10},
	 {DISPCTRL_WR_DATA, 0x53},

	 {DISPCTRL_WR_CMND, 0x11},
	 {DISPCTRL_WR_DATA, 0x00},

	 {DISPCTRL_WR_CMND, 0x12},
	 {DISPCTRL_WR_DATA, 0x00},

	 {DISPCTRL_WR_CMND, 0x14},
	 {DISPCTRL_WR_DATA, 0x01},

	 {DISPCTRL_WR_CMND, 0x15},
	 {DISPCTRL_WR_DATA, 0x00},

	 {DISPCTRL_WR_CMND, 0x16},
	 {DISPCTRL_WR_DATA, 0x05},

	 {DISPCTRL_WR_CMND, 0x17},
	 {DISPCTRL_WR_DATA, 0x00},

	 {DISPCTRL_WR_CMND, 0x19},
	 {DISPCTRL_WR_DATA, 0x7F},

	 {DISPCTRL_WR_CMND, 0x1A},
	 {DISPCTRL_WR_DATA, 0xFF},

	 {DISPCTRL_WR_CMND, 0x1B},
	 {DISPCTRL_WR_DATA, 0x0F},

	 {DISPCTRL_WR_CMND, 0x1C},
	 {DISPCTRL_WR_DATA, 0x00},

	 {DISPCTRL_WR_CMND, 0x1D},
	 {DISPCTRL_WR_DATA, 0x00},

	 {DISPCTRL_WR_CMND, 0x1E},
	 {DISPCTRL_WR_DATA, 0x00},

	 {DISPCTRL_WR_CMND, 0x1F},
	 {DISPCTRL_WR_DATA, 0x07},

	 {DISPCTRL_WR_CMND, 0x20},
	 {DISPCTRL_WR_DATA, 0x00},

	 {DISPCTRL_WR_CMND, 0x21},
	 {DISPCTRL_WR_DATA, 0x00},

	 {DISPCTRL_WR_CMND, 0x22},
	 {DISPCTRL_WR_DATA, 0x55},

	 {DISPCTRL_WR_CMND, 0x23},
	 {DISPCTRL_WR_DATA, 0x4D},

	 {DISPCTRL_WR_CMND, 0x2D},
	 {DISPCTRL_WR_DATA, 0x02},

	 {DISPCTRL_WR_CMND, 0x83},
	 {DISPCTRL_WR_DATA, 0x01},

	 {DISPCTRL_WR_CMND, 0x9E},
	 {DISPCTRL_WR_DATA, 0x58},

	 {DISPCTRL_WR_CMND, 0x9F},
	 {DISPCTRL_WR_DATA, 0x6A},

	 {DISPCTRL_WR_CMND, 0xA0},
	 {DISPCTRL_WR_DATA, 0x01},

	 {DISPCTRL_WR_CMND, 0xA2},
	 {DISPCTRL_WR_DATA, 0x10},

	 {DISPCTRL_WR_CMND, 0xBB},
	 {DISPCTRL_WR_DATA, 0x0A},

	 {DISPCTRL_WR_CMND, 0xBC},
	 {DISPCTRL_WR_DATA, 0x0A},

	 {DISPCTRL_WR_CMND, 0x28},
	 {DISPCTRL_WR_DATA, 0x01},

	 {DISPCTRL_WR_CMND, 0x2F},
	 {DISPCTRL_WR_DATA, 0x02},

	 {DISPCTRL_WR_CMND, 0x32},
	 {DISPCTRL_WR_DATA, 0x08},

	 {DISPCTRL_WR_CMND, 0x33},
	 {DISPCTRL_WR_DATA, 0xB8},

	 {DISPCTRL_WR_CMND, 0x36},
	 {DISPCTRL_WR_DATA, 0x01},

	 {DISPCTRL_WR_CMND, 0x37},
	 {DISPCTRL_WR_DATA, 0x00},

	 {DISPCTRL_WR_CMND, 0x43},
	 {DISPCTRL_WR_DATA, 0x00},

	 {DISPCTRL_WR_CMND, 0x4B},
	 {DISPCTRL_WR_DATA, 0x21},

	 {DISPCTRL_WR_CMND, 0x4C},
	 {DISPCTRL_WR_DATA, 0x03},

	 {DISPCTRL_WR_CMND, 0x50},
	 {DISPCTRL_WR_DATA, 0x21},

	 {DISPCTRL_WR_CMND, 0x51},
	 {DISPCTRL_WR_DATA, 0x03},

	 {DISPCTRL_WR_CMND, 0x58},
	 {DISPCTRL_WR_DATA, 0x21},

	 {DISPCTRL_WR_CMND, 0x59},
	 {DISPCTRL_WR_DATA, 0x03},

	 {DISPCTRL_WR_CMND, 0x5D},
	 {DISPCTRL_WR_DATA, 0x21},

	 {DISPCTRL_WR_CMND, 0x5E},
	 {DISPCTRL_WR_DATA, 0x03},

	 {DISPCTRL_WR_CMND, 0x6C},
	 {DISPCTRL_WR_DATA, 0x00},

	 {DISPCTRL_WR_CMND, 0x6D},
	 {DISPCTRL_WR_DATA, 0x00},

	 {DISPCTRL_WR_CMND, /* R+*/ 0x75},
	 {DISPCTRL_WR_DATA, 0x00},
	 {DISPCTRL_WR_DATA, 0x98},
	 {DISPCTRL_WR_DATA, 0x00},
	 {DISPCTRL_WR_DATA, 0xAF},
	 {DISPCTRL_WR_DATA, 0x00},
	 {DISPCTRL_WR_DATA, 0xD1},
	 {DISPCTRL_WR_DATA, 0x00},
	 {DISPCTRL_WR_DATA, 0xE9},
	 {DISPCTRL_WR_DATA, 0x00},
	 {DISPCTRL_WR_DATA, 0xFE},
	 {DISPCTRL_WR_DATA, 0x01},
	 {DISPCTRL_WR_DATA, 0x10},
	 {DISPCTRL_WR_DATA, 0x01},
	 {DISPCTRL_WR_DATA, 0x20},
	 {DISPCTRL_WR_DATA, 0x01},
	 {DISPCTRL_WR_DATA, 0x2E},
	 {DISPCTRL_WR_DATA, 0x01},
	 {DISPCTRL_WR_DATA, 0x3B},
	 {DISPCTRL_WR_DATA, 0x01},
	 {DISPCTRL_WR_DATA, 0x65},
	 {DISPCTRL_WR_DATA, 0x01},
	 {DISPCTRL_WR_DATA, 0x88},
	 {DISPCTRL_WR_DATA, 0x01},
	 {DISPCTRL_WR_DATA, 0xBD},
	 {DISPCTRL_WR_DATA, 0x01},
	 {DISPCTRL_WR_DATA, 0xE7},
	 {DISPCTRL_WR_DATA, 0x02},
	 {DISPCTRL_WR_DATA, 0x27},
	 {DISPCTRL_WR_DATA, 0x02},
	 {DISPCTRL_WR_DATA, 0x59},
	 {DISPCTRL_WR_DATA, 0x02},
	 {DISPCTRL_WR_DATA, 0x5B},
	 {DISPCTRL_WR_DATA, 0x02},
	 {DISPCTRL_WR_DATA, 0x87},
	 {DISPCTRL_WR_DATA, 0x02},
	 {DISPCTRL_WR_DATA, 0xB6},
	 {DISPCTRL_WR_DATA, 0x02},
	 {DISPCTRL_WR_DATA, 0xD5},
	 {DISPCTRL_WR_DATA, 0x02},
	 {DISPCTRL_WR_DATA, 0xFD},
	 {DISPCTRL_WR_DATA, 0x03},
	 {DISPCTRL_WR_DATA, 0x19},
	 {DISPCTRL_WR_DATA, 0x03},
	 {DISPCTRL_WR_DATA, 0x40},
	 {DISPCTRL_WR_DATA, 0x03},
	 {DISPCTRL_WR_DATA, 0x4C},
	 {DISPCTRL_WR_DATA, 0x03},
	 {DISPCTRL_WR_DATA, 0x59},
	 {DISPCTRL_WR_DATA, 0x03},
	 {DISPCTRL_WR_DATA, 0x67},
	 {DISPCTRL_WR_DATA, 0x03},
	 {DISPCTRL_WR_DATA, 0x78},
	 {DISPCTRL_WR_DATA, 0x03},
	 {DISPCTRL_WR_DATA, 0x8A},
	 {DISPCTRL_WR_DATA, 0x03},
	 {DISPCTRL_WR_DATA, 0xA8},
	 {DISPCTRL_WR_DATA, 0x03},
	 {DISPCTRL_WR_DATA, 0xB8},
	 {DISPCTRL_WR_DATA, 0x03},
	 {DISPCTRL_WR_DATA, 0xBE},
	 {DISPCTRL_WR_DATA, 0x00},
	 {DISPCTRL_WR_DATA, 0x98},
	 {DISPCTRL_WR_DATA, 0x00},
	 {DISPCTRL_WR_DATA, 0xAF},
	 {DISPCTRL_WR_DATA, 0x00},
	 {DISPCTRL_WR_DATA, 0xD1},
	 {DISPCTRL_WR_DATA, 0x00},
	 {DISPCTRL_WR_DATA, 0xE9},
	 {DISPCTRL_WR_DATA, 0x00},
	 {DISPCTRL_WR_DATA, 0xFE},
	 {DISPCTRL_WR_DATA, 0x01},
	 {DISPCTRL_WR_DATA, 0x10},
	 {DISPCTRL_WR_DATA, 0x01},
	 {DISPCTRL_WR_DATA, 0x20},
	 {DISPCTRL_WR_DATA, 0x01},
	 {DISPCTRL_WR_DATA, 0x2E},
	 {DISPCTRL_WR_DATA, 0x01},
	 {DISPCTRL_WR_DATA, 0x3B},
	 {DISPCTRL_WR_DATA, 0x01},
	 {DISPCTRL_WR_DATA, 0x65},
	 {DISPCTRL_WR_DATA, 0x01},
	 {DISPCTRL_WR_DATA, 0x88},
	 {DISPCTRL_WR_DATA, 0x01},
	 {DISPCTRL_WR_DATA, 0xBD},
	 {DISPCTRL_WR_DATA, 0x01},
	 {DISPCTRL_WR_DATA, 0xE7},
	 {DISPCTRL_WR_DATA, 0x02},
	 {DISPCTRL_WR_DATA, 0x27},
	 {DISPCTRL_WR_DATA, 0x02},
	 {DISPCTRL_WR_DATA, 0x59},
	 {DISPCTRL_WR_DATA, 0x02},
	 {DISPCTRL_WR_DATA, 0x5B},
	 {DISPCTRL_WR_DATA, 0x02},
	 {DISPCTRL_WR_DATA, 0x87},
	 {DISPCTRL_WR_DATA, 0x02},
	 {DISPCTRL_WR_DATA, 0xB6},
	 {DISPCTRL_WR_DATA, 0x02},
	 {DISPCTRL_WR_DATA, 0xD5},
	 {DISPCTRL_WR_DATA, 0x02},
	 {DISPCTRL_WR_DATA, 0xFD},
	 {DISPCTRL_WR_DATA, 0x03},
	 {DISPCTRL_WR_DATA, 0x19},
	 {DISPCTRL_WR_DATA, 0x03},
	 {DISPCTRL_WR_DATA, 0x40},
	 {DISPCTRL_WR_DATA, 0x03},
	 {DISPCTRL_WR_DATA, 0x4C},
	 {DISPCTRL_WR_DATA, 0x03},
	 {DISPCTRL_WR_DATA, 0x59},
	 {DISPCTRL_WR_DATA, 0x03},
	 {DISPCTRL_WR_DATA, 0x67},
	 {DISPCTRL_WR_DATA, 0x03},
	 {DISPCTRL_WR_DATA, 0x78},
	 {DISPCTRL_WR_DATA, 0x03},
	 {DISPCTRL_WR_DATA, 0x8A},
	 {DISPCTRL_WR_DATA, 0x03},
	 {DISPCTRL_WR_DATA, 0xA8},
	 {DISPCTRL_WR_DATA, 0x03},
	 {DISPCTRL_WR_DATA, 0xB8},
	 {DISPCTRL_WR_DATA, 0x03},
	 {DISPCTRL_WR_DATA, 0xBE},
	 {DISPCTRL_WR_DATA, 0x00},
	 {DISPCTRL_WR_DATA, 0x98},
	 {DISPCTRL_WR_DATA, 0x00},
	 {DISPCTRL_WR_DATA, 0xAF},
	 {DISPCTRL_WR_DATA, 0x00},
	 {DISPCTRL_WR_DATA, 0xD1},
	 {DISPCTRL_WR_DATA, 0x00},
	 {DISPCTRL_WR_DATA, 0xE9},
	 {DISPCTRL_WR_DATA, 0x00},
	 {DISPCTRL_WR_DATA, 0xFE},
	 {DISPCTRL_WR_DATA, 0x01},
	 {DISPCTRL_WR_DATA, 0x10},

	 {DISPCTRL_WR_CMND, 0xFF},
	 {DISPCTRL_WR_DATA, 0x02},

	 {DISPCTRL_WR_CMND, 0x00},
	 {DISPCTRL_WR_DATA, 0x01},
	 {DISPCTRL_WR_DATA, 0x20},
	 {DISPCTRL_WR_DATA, 0x01},
	 {DISPCTRL_WR_DATA, 0x2E},
	 {DISPCTRL_WR_DATA, 0x01},
	 {DISPCTRL_WR_DATA, 0x3B},
	 {DISPCTRL_WR_DATA, 0x01},
	 {DISPCTRL_WR_DATA, 0x65},
	 {DISPCTRL_WR_DATA, 0x01},
	 {DISPCTRL_WR_DATA, 0x88},
	 {DISPCTRL_WR_DATA, 0x01},
	 {DISPCTRL_WR_DATA, 0xBD},
	 {DISPCTRL_WR_DATA, 0x01},
	 {DISPCTRL_WR_DATA, 0xE7},
	 {DISPCTRL_WR_DATA, 0x02},
	 {DISPCTRL_WR_DATA, 0x27},
	 {DISPCTRL_WR_DATA, 0x02},
	 {DISPCTRL_WR_DATA, 0x59},
	 {DISPCTRL_WR_DATA, 0x02},
	 {DISPCTRL_WR_DATA, 0x5B},
	 {DISPCTRL_WR_DATA, 0x02},
	 {DISPCTRL_WR_DATA, 0x87},
	 {DISPCTRL_WR_DATA, 0x02},
	 {DISPCTRL_WR_DATA, 0xB6},
	 {DISPCTRL_WR_DATA, 0x02},
	 {DISPCTRL_WR_DATA, 0xD5},
	 {DISPCTRL_WR_DATA, 0x02},
	 {DISPCTRL_WR_DATA, 0xFD},
	 {DISPCTRL_WR_DATA, 0x03},
	 {DISPCTRL_WR_DATA, 0x19},
	 {DISPCTRL_WR_DATA, 0x03},
	 {DISPCTRL_WR_DATA, 0x40},
	 {DISPCTRL_WR_DATA, 0x03},
	 {DISPCTRL_WR_DATA, 0x4C},
	 {DISPCTRL_WR_DATA, 0x03},
	 {DISPCTRL_WR_DATA, 0x59},
	 {DISPCTRL_WR_DATA, 0x03},
	 {DISPCTRL_WR_DATA, 0x67},
	 {DISPCTRL_WR_DATA, 0x03},
	 {DISPCTRL_WR_DATA, 0x78},
	 {DISPCTRL_WR_DATA, 0x03},
	 {DISPCTRL_WR_DATA, 0x8A},
	 {DISPCTRL_WR_DATA, 0x03},
	 {DISPCTRL_WR_DATA, 0xA8},
	 {DISPCTRL_WR_DATA, 0x03},
	 {DISPCTRL_WR_DATA, 0xB8},
	 {DISPCTRL_WR_DATA, 0x03},
	 {DISPCTRL_WR_DATA, 0xBE},
	 {DISPCTRL_WR_DATA, /* G - */
		0x00},
	 {DISPCTRL_WR_DATA, 0x98},
	 {DISPCTRL_WR_DATA, 0x00},
	 {DISPCTRL_WR_DATA, 0xAF},
	 {DISPCTRL_WR_DATA, 0x00},
	 {DISPCTRL_WR_DATA, 0xD1},
	 {DISPCTRL_WR_DATA, 0x00},
	 {DISPCTRL_WR_DATA, 0xE9},
	 {DISPCTRL_WR_DATA, 0x00},
	 {DISPCTRL_WR_DATA, 0xFE},
	 {DISPCTRL_WR_DATA, 0x01},
	 {DISPCTRL_WR_DATA, 0x10},
	 {DISPCTRL_WR_DATA, 0x01},
	 {DISPCTRL_WR_DATA, 0x20},
	 {DISPCTRL_WR_DATA, 0x01},
	 {DISPCTRL_WR_DATA, 0x2E},
	 {DISPCTRL_WR_DATA, 0x01},
	 {DISPCTRL_WR_DATA, 0x3B},
	 {DISPCTRL_WR_DATA, 0x01},
	 {DISPCTRL_WR_DATA, 0x65},
	 {DISPCTRL_WR_DATA, 0x01},
	 {DISPCTRL_WR_DATA, 0x88},
	 {DISPCTRL_WR_DATA, 0x01},
	 {DISPCTRL_WR_DATA, 0xBD},
	 {DISPCTRL_WR_DATA, 0x01},
	 {DISPCTRL_WR_DATA, 0xE7},
	 {DISPCTRL_WR_DATA, 0x02},
	 {DISPCTRL_WR_DATA, 0x27},
	 {DISPCTRL_WR_DATA, 0x02},
	 {DISPCTRL_WR_DATA, 0x59},
	 {DISPCTRL_WR_DATA, 0x02},
	 {DISPCTRL_WR_DATA, 0x5B},
	 {DISPCTRL_WR_DATA, 0x02},
	 {DISPCTRL_WR_DATA, 0x87},
	 {DISPCTRL_WR_DATA, 0x02},
	 {DISPCTRL_WR_DATA, 0xB6},
	 {DISPCTRL_WR_DATA, 0x02},
	 {DISPCTRL_WR_DATA, 0xD5},
	 {DISPCTRL_WR_DATA, 0x02},
	 {DISPCTRL_WR_DATA, 0xFD},
	 {DISPCTRL_WR_DATA, 0x03},
	 {DISPCTRL_WR_DATA, 0x19},
	 {DISPCTRL_WR_DATA, 0x03},
	 {DISPCTRL_WR_DATA, 0x40},
	 {DISPCTRL_WR_DATA, 0x03},
	 {DISPCTRL_WR_DATA, 0x4C},
	 {DISPCTRL_WR_DATA, 0x03},
	 {DISPCTRL_WR_DATA, 0x59},
	 {DISPCTRL_WR_DATA, 0x03},
	 {DISPCTRL_WR_DATA, 0x67},
	 {DISPCTRL_WR_DATA, 0x03},
	 {DISPCTRL_WR_DATA, 0x78},
	 {DISPCTRL_WR_DATA, 0x03},
	 {DISPCTRL_WR_DATA, 0x8A},
	 {DISPCTRL_WR_DATA, 0x03},
	 {DISPCTRL_WR_DATA, 0xA8},
	 {DISPCTRL_WR_DATA, 0x03},
	 {DISPCTRL_WR_DATA, 0xB8},
	 {DISPCTRL_WR_DATA, 0x03},
	 {DISPCTRL_WR_DATA, 0xBE},
	 {DISPCTRL_WR_DATA, /* B + */
		0x00},
	 {DISPCTRL_WR_DATA, 0x98},
	 {DISPCTRL_WR_DATA, 0x00},
	 {DISPCTRL_WR_DATA, 0xAF},
	 {DISPCTRL_WR_DATA, 0x00},
	 {DISPCTRL_WR_DATA, 0xD1},
	 {DISPCTRL_WR_DATA, 0x00},
	 {DISPCTRL_WR_DATA, 0xE9},
	 {DISPCTRL_WR_DATA, 0x00},
	 {DISPCTRL_WR_DATA, 0xFE},
	 {DISPCTRL_WR_DATA, 0x01},
	 {DISPCTRL_WR_DATA, 0x10},
	 {DISPCTRL_WR_DATA, 0x01},
	 {DISPCTRL_WR_DATA, 0x20},
	 {DISPCTRL_WR_DATA, 0x01},
	 {DISPCTRL_WR_DATA, 0x2E},
	 {DISPCTRL_WR_DATA, 0x01},
	 {DISPCTRL_WR_DATA, 0x3B},
	 {DISPCTRL_WR_DATA, 0x01},
	 {DISPCTRL_WR_DATA, 0x65},
	 {DISPCTRL_WR_DATA, 0x01},
	 {DISPCTRL_WR_DATA, 0x88},
	 {DISPCTRL_WR_DATA, 0x01},
	 {DISPCTRL_WR_DATA, 0xBD},
	 {DISPCTRL_WR_DATA, 0x01},
	 {DISPCTRL_WR_DATA, 0xE7},
	 {DISPCTRL_WR_DATA, 0x02},
	 {DISPCTRL_WR_DATA, 0x27},
	 {DISPCTRL_WR_DATA, 0x02},
	 {DISPCTRL_WR_DATA, 0x59},
	 {DISPCTRL_WR_DATA, 0x02},
	 {DISPCTRL_WR_DATA, 0x5B},
	 {DISPCTRL_WR_DATA, 0x02},
	 {DISPCTRL_WR_DATA, 0x87},
	 {DISPCTRL_WR_DATA, 0x02},
	 {DISPCTRL_WR_DATA, 0xB6},
	 {DISPCTRL_WR_DATA, 0x02},
	 {DISPCTRL_WR_DATA, 0xD5},
	 {DISPCTRL_WR_DATA, 0x02},
	 {DISPCTRL_WR_DATA, 0xFD},
	 {DISPCTRL_WR_DATA, 0x03},
	 {DISPCTRL_WR_DATA, 0x19},
	 {DISPCTRL_WR_DATA, 0x03},
	 {DISPCTRL_WR_DATA, 0x40},
	 {DISPCTRL_WR_DATA, 0x03},
	 {DISPCTRL_WR_DATA, 0x4C},
	 {DISPCTRL_WR_DATA, 0x03},
	 {DISPCTRL_WR_DATA, 0x59},
	 {DISPCTRL_WR_DATA, 0x03},
	 {DISPCTRL_WR_DATA, 0x67},
	 {DISPCTRL_WR_DATA, 0x03},
	 {DISPCTRL_WR_DATA, 0x78},
	 {DISPCTRL_WR_DATA, 0x03},
	 {DISPCTRL_WR_DATA, 0x8A},
	 {DISPCTRL_WR_DATA, 0x03},
	 {DISPCTRL_WR_DATA, 0xA8},
	 {DISPCTRL_WR_DATA, 0x03},
	 {DISPCTRL_WR_DATA, 0xB8},
	 {DISPCTRL_WR_DATA, 0x03},
	 {DISPCTRL_WR_DATA, 0xBE},
	 {DISPCTRL_WR_DATA, /* B - */
		0x00},
	 {DISPCTRL_WR_DATA, 0x98},
	 {DISPCTRL_WR_DATA, 0x00},
	 {DISPCTRL_WR_DATA, 0xAF},
	 {DISPCTRL_WR_DATA, 0x00},
	 {DISPCTRL_WR_DATA, 0xD1},
	 {DISPCTRL_WR_DATA, 0x00},
	 {DISPCTRL_WR_DATA, 0xE9},
	 {DISPCTRL_WR_DATA, 0x00},
	 {DISPCTRL_WR_DATA, 0xFE},
	 {DISPCTRL_WR_DATA, 0x01},
	 {DISPCTRL_WR_DATA, 0x10},
	 {DISPCTRL_WR_DATA, 0x01},
	 {DISPCTRL_WR_DATA, 0x20},
	 {DISPCTRL_WR_DATA, 0x01},
	 {DISPCTRL_WR_DATA, 0x2E},
	 {DISPCTRL_WR_DATA, 0x01},
	 {DISPCTRL_WR_DATA, 0x3B},
	 {DISPCTRL_WR_DATA, 0x01},
	 {DISPCTRL_WR_DATA, 0x65},
	 {DISPCTRL_WR_DATA, 0x01},
	 {DISPCTRL_WR_DATA, 0x88},
	 {DISPCTRL_WR_DATA, 0x01},
	 {DISPCTRL_WR_DATA, 0xBD},
	 {DISPCTRL_WR_DATA, 0x01},
	 {DISPCTRL_WR_DATA, 0xE7},
	 {DISPCTRL_WR_DATA, 0x02},
	 {DISPCTRL_WR_DATA, 0x27},
	 {DISPCTRL_WR_DATA, 0x02},
	 {DISPCTRL_WR_DATA, 0x59},
	 {DISPCTRL_WR_DATA, 0x02},
	 {DISPCTRL_WR_DATA, 0x5B},
	 {DISPCTRL_WR_DATA, 0x02},
	 {DISPCTRL_WR_DATA, 0x87},
	 {DISPCTRL_WR_DATA, 0x02},
	 {DISPCTRL_WR_DATA, 0xB6},
	 {DISPCTRL_WR_DATA, 0x02},
	 {DISPCTRL_WR_DATA, 0xD5},
	 {DISPCTRL_WR_DATA, 0x02},
	 {DISPCTRL_WR_DATA, 0xFD},
	 {DISPCTRL_WR_DATA, 0x03},
	 {DISPCTRL_WR_DATA, 0x19},
	 {DISPCTRL_WR_DATA, 0x03},
	 {DISPCTRL_WR_DATA, 0x40},
	 {DISPCTRL_WR_DATA, 0x03},
	 {DISPCTRL_WR_DATA, 0x4C},
	 {DISPCTRL_WR_DATA, 0x03},
	 {DISPCTRL_WR_DATA, 0x59},
	 {DISPCTRL_WR_DATA, 0x03},
	 {DISPCTRL_WR_DATA, 0x67},
	 {DISPCTRL_WR_DATA, 0x03},
	 {DISPCTRL_WR_DATA, 0x78},
	 {DISPCTRL_WR_DATA, 0x03},
	 {DISPCTRL_WR_DATA, 0x8A},
	 {DISPCTRL_WR_DATA, 0x03},
	 {DISPCTRL_WR_DATA, 0xA8},
	 {DISPCTRL_WR_DATA, 0x03},
	 {DISPCTRL_WR_DATA, 0xB8},
	 {DISPCTRL_WR_DATA, 0x03},
	 {DISPCTRL_WR_DATA, 0xBE},

	 {DISPCTRL_WR_CMND, 0xFF},
	 {DISPCTRL_WR_DATA, 0x00},

	 {DISPCTRL_WR_CMND, 0xFB},
	 {DISPCTRL_WR_DATA, 0x01},

	 {DISPCTRL_WR_CMND, 0xBA},
	 {DISPCTRL_WR_DATA, 0x03},

	 {DISPCTRL_WR_CMND, 0xC2},
	 {DISPCTRL_WR_DATA, 0x08},

	 {DISPCTRL_WR_CMND, 0x35},
	 {DISPCTRL_WR_DATA, 0x00},

	 {DISPCTRL_WR_CMND, 0x44},
	 {DISPCTRL_WR_DATA, (NT35590_TE_SCAN_LINE & 0xFF00) >> 8},
	 {DISPCTRL_WR_DATA, (NT35590_TE_SCAN_LINE & 0xFF)},

	 {DISPCTRL_WR_CMND, 0xFF},
	 {DISPCTRL_WR_DATA, 0x00},

	 {DISPCTRL_WR_CMND, 0xFB},
	 {DISPCTRL_WR_DATA, 0x01},

	 {DISPCTRL_WR_CMND, 0xFF},
	 {DISPCTRL_WR_DATA, 0x01},

	 {DISPCTRL_WR_CMND, 0xFB},
	 {DISPCTRL_WR_DATA, 0x01},

	 {DISPCTRL_WR_CMND, 0xFF},
	 {DISPCTRL_WR_DATA, 0x02},

	 {DISPCTRL_WR_CMND, 0xFB},
	 {DISPCTRL_WR_DATA, 0x01},

	 {DISPCTRL_WR_CMND, 0xFF},
	 {DISPCTRL_WR_DATA, 0x03},

	 {DISPCTRL_WR_CMND, 0xFB},
	 {DISPCTRL_WR_DATA, 0x01},

	 {DISPCTRL_WR_CMND, 0xFF},
	 {DISPCTRL_WR_DATA, 0x04},

	 {DISPCTRL_WR_CMND, 0xFB},
	 {DISPCTRL_WR_DATA, 0x01},

	 {DISPCTRL_WR_CMND, 0xFF},
	 {DISPCTRL_WR_DATA, 0x05},

	 {DISPCTRL_WR_CMND, 0xFB},
	 {DISPCTRL_WR_DATA, 0x01},

	 {DISPCTRL_WR_CMND, 0xFF},
	 {DISPCTRL_WR_DATA, 0x00},

	 {DISPCTRL_WR_CMND, 0xFB},
	 {DISPCTRL_WR_DATA, 0x01},

	 {DISPCTRL_WR_CMND, 0x11},
	 {DISPCTRL_WR_DATA, 0x00},
	 {DISPCTRL_SLEEP_MS, 120},

	 {DISPCTRL_WR_CMND, 0x51},
	 {DISPCTRL_WR_DATA, 0xFF},

	 {DISPCTRL_WR_CMND, 0x53},
	 {DISPCTRL_WR_DATA, 0x2C},

	 {DISPCTRL_WR_CMND, 0x55},
	 {DISPCTRL_WR_DATA, 0x00},

	 {DISPCTRL_WR_CMND, 0x29},
	 {DISPCTRL_WR_DATA, 0x00},
	 {DISPCTRL_DRAW_BLACK, 0},
	 {DISPCTRL_LIST_END, 0},
};

static struct dispctrl_rec nt35590_suspend_cmd[] __initdata = {
	 {DISPCTRL_WR_CMND, 0x28},
	 {DISPCTRL_WR_DATA, 0x00},

	 {DISPCTRL_WR_CMND, 0x10},
	 {DISPCTRL_WR_DATA, 0x00},
	 {DISPCTRL_SLEEP_MS, 120},
	 {DISPCTRL_LIST_END, 0},
};

static struct dispctrl_rec nt35590_panel_id_seq[] __initdata = {
	{DISPCTRL_WR_CMND, RDID1},
	{DISPCTRL_WR_DATA, 0x00},
	{DISPCTRL_WR_CMND, RDID2},
	{DISPCTRL_WR_DATA, 0x80},
	{DISPCTRL_WR_CMND, RDID3},
	{DISPCTRL_WR_DATA, 0x00},
	{DISPCTRL_LIST_END, 0},
};

struct lcd_config nt35590_config __initdata = {
	.name = "NT35590",
	.modes_supp = LCD_CMD_VID_BOTH,
	.pack_send_mode = RT_DISPLAY_SEND_MODE_HS,
	.max_lanes = 4,
	.phy_width = 54,
	.phy_height = 95,
	.width = 720,
	.height = 1280,
	.hbp = 100,
	.hfp = 8,
	.hsync = 7,
	.vbp = 8,
	.vfp = 10,
	.vsync = 5,
	.setup = 1000, /*TODO: pass these values as platform data */
	.pulse = 5000,
	.init_seq_cmd = nt35590_initialize_cmd,
	.init_seq_min = NULL,
	.suspend_seq = nt35590_suspend_cmd,
	.panel_id = &nt35590_panel_id_seq[0],
	.verify_id = false,
	.color_mode = RGB888,
	.vburst_mode = LCD_VID_NON_BURST_SYNC_EVENT,
	.max_hs_bps = 500 * 1000000,
	.cont_clock = 1,
	.cmd_transmission = 1,
	.time_param = &nt35590_time_param,
};



