#
# Makefile for the FT5336 touchscreen drivers.
#

# Each configuration option enables a list of files.
#obj-$(CONFIG_TOUCHSCREEN_FT5336)        += ft5336.o ft5336_ex_fun.o focal_mcap_test_lib.a
obj-$(CONFIG_TOUCHSCREEN_FT5336)	+= ft5336.o ft5336_ex_fun.o